INSERT INTO [R2Parm].[dbo].[Abnormal]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[APercent]
      ,[ATime]
      ,[AGrade]
      ,[ADesc]
  FROM [FNLParm].[dbo].[DT_Abnormal]
  
INSERT INTO [R2Parm].[dbo].[AbnormalAdd]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[APercent]
  FROM [FNLParm].[dbo].[DT_AbnormalAdd]
 
INSERT INTO [R2Parm].[dbo].[AbnormalAttrApply]
SELECT [mID]
      ,[mOriginAID]
      ,[mOriginAType]
      ,[mConditionAID]
      ,[mDesc]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrApply]
 
INSERT INTO [R2Parm].[dbo].[AbnormalAttrAttach]
SELECT [mID]
      ,[mOriginAID]
      ,[mEffectAID]
      ,[mConditionType]
      ,[mConditionAType]
      ,[mDesc]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrAttach]
 
INSERT INTO [R2Parm].[dbo].[AbnormalAttrChangeAbnormal]
SELECT [mID]
      ,[mOriginAID]
      ,[mEffectAID]
      ,[mConditionType]
      ,[mConditionAID]
      ,[mDesc]
      ,[mConditionAType]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrChangeAbnormal]
 
INSERT INTO [R2Parm].[dbo].[AbnormalAttrChangeEquipAbnormal]
SELECT [mID]
      ,[mConditionAID]
      ,[mOriginAType]
      ,[mOriginAItemNo]
      ,[mEffectAID]
      ,[mDesc]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrChangeEquipAbnormal]
 
INSERT INTO [R2Parm].[dbo].[AbnormalAttrDetach]
SELECT [mID]
      ,[mAppType]
      ,[mOriginAID]
      ,[mEffectAType]
      ,[mConditionType]
      ,[mConditionAType]
      ,[mDesc]
      ,[mEffectAID]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrDetach]
 
 INSERT INTO [R2Parm].[dbo].[AbnormalAttrIgnore]
SELECT [mID]
      ,[mOriginAID]
      ,[mConditionType]
      ,[mConditionAType]
      ,[mIsComplex]
      ,[mDesc]
      ,[mConditionAID]
  FROM [FNLParm].[dbo].[DT_AbnormalAttrIgnore]
 
INSERT INTO [R2Parm].[dbo].[AbnormalModule]
SELECT [AID]
      ,[MID]
  FROM [FNLParm].[dbo].[DT_AbnormalModule]
 
INSERT INTO [R2Parm].[dbo].[AbnormalModule]
SELECT [AID]
      ,[MID]
  FROM [FNLParm].[dbo].[DT_AbnormalModule]
 
 INSERT INTO [R2Parm].[dbo].[AbnormalResist]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[APercent]
  FROM [FNLParm].[dbo].[DT_AbnormalResist]
 
 INSERT INTO [R2Parm].[dbo].[AbnormalType]
SELECT [AType]
      ,[AName]
      ,[AEffect]
      ,[ARemovable]
      ,[AFileName]
      ,[AIconX]
      ,[AIconY]
      ,[ACopyable]
  FROM [FNLParm].[dbo].[TP_AbnormalType]
 
 INSERT INTO [R2Parm].[dbo].[Attribute]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[ADiceDamage]
      ,[ADamage]
  FROM [FNLParm].[dbo].[DT_Attribute]
 
 INSERT INTO [R2Parm].[dbo].[AttributeAdd]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[ADiceDamage]
      ,[ADamage]
  FROM [FNLParm].[dbo].[DT_AttributeAdd]
 
 INSERT INTO [R2Parm].[dbo].[AttributeResist]
SELECT [AID]
      ,[AType]
      ,[ALevel]
      ,[ADamage]
      ,[ADiceDamage]
  FROM [FNLParm].[dbo].[DT_AttributeResist]
 
 INSERT INTO [R2Parm].[dbo].[Bead]
SELECT [IID]
      ,[mTargetIPos]
      ,[mProb]
      ,[mGroup]
      ,[mItemSubType]
  FROM [FNLParm].[dbo].[DT_Bead]

INSERT INTO [R2Parm].[dbo].[BeadEffect]
SELECT [mBeadNo]
      ,[mName]
      ,[mBeadType]
      ,[mChkGroup]
      ,[mPercent]
      ,[mApplyTarget]
      ,[mParamA]
      ,[mParamB]
      ,[mParamC]
      ,[mParamD]
      ,[mParamE]
  FROM [FNLParm].[dbo].[DT_BeadEffect]
 
 INSERT INTO [R2Parm].[dbo].[BeadEffectParm]
SELECT [mBeadNo]
      ,[mOrderNo]
      ,[mParamA]
      ,[mParamB]
      ,[mParamC]
      ,[mParamD]
      ,[mParamE]
  FROM [FNLParm].[dbo].[DT_BeadEffectParm]
 
 INSERT INTO [R2Parm].[dbo].[Dialog]
SELECT [mRegDate]
      ,[mMId]
      ,[mClick]
      ,[mDie]
      ,[mAttacked]
      ,[mTarget]
      ,[mBear]
      ,[mGossip1]
      ,[mGossip2]
      ,[mGossip3]
      ,[mGossip4]
      ,[mUptDate]
  FROM [FNLParm].[dbo].[TblDialog]
 
 INSERT INTO [R2Parm].[dbo].[DialogScript]
SELECT [mRegDate]
      ,[mMId]
      ,[mScriptText]
      ,[mUptDate]
  FROM [FNLParm].[dbo].[TblDialogScript]
 
 INSERT INTO [R2Parm].[dbo].[DropGroup]
SELECT [DGroup]
      ,[DDrop]
      ,[DPercent]
  FROM [FNLParm].[dbo].[DT_DropGroup]
 
 INSERT INTO [R2Parm].[dbo].[DropItem]
SELECT [DDrop]
      ,[DItem]
      ,[DNumber]
      ,[DStatus]
      ,[DIsEvent]
  FROM [FNLParm].[dbo].[DT_DropItem]
 
 INSERT INTO [R2Parm].[dbo].[Exp]
SELECT [ELevel]
      ,[EExp]
      ,[ERestExpRate]
  FROM [FNLParm].[dbo].[DT_Exp]
 
 INSERT INTO [R2Parm].[dbo].[FullMoonMonsterList]
SELECT [mMID]
      ,[mIsFullMoon]
  FROM [FNLParm].[dbo].[TblFullMoonMonsterList]
 
INSERT INTO [R2Parm].[dbo].[Item]
SELECT [IID]
      ,[IName]
      ,[IType]
      ,[ILevel]
      ,[IDHIT]
      ,[IDDD]
      ,[IRHIT]
      ,[IRDD]
      ,[IMHIT]
      ,[IMDD]
      ,[IHPPlus]
      ,[IMPPlus]
      ,[ISTR]
      ,[IDEX]
      ,[IINT]
      ,[IMaxStack]
      ,[IWeight]
      ,[IUseType]
      ,[IUseNum]
      ,[IRecycle]
      ,[IHPRegen]
      ,[IMPRegen]
      ,[IAttackRate]
      ,[IMoveRate]
      ,[ICritical]
      ,[ITermOfValidity]
      ,[ITermOfValidityMi]
      ,[IDesc]
      ,[IStatus]
      ,[IFakeID]
      ,[IFakeName]
      ,[IUseMsg]
      ,[IRange]
      ,[IUseClass]
      ,[IDropEffect]
      ,[IUseLevel]
      ,[IUseEternal]
      ,[IUseDelay]
      ,[IUseInAttack]
      ,[IIsEvent]
      ,[IIsIndict]
      ,[IAddWeight]
      ,[ISubType]
      ,[IIsCharge]
      ,[INationOp]
      ,[IPShopItemType]
      ,[IQuestNo]
      ,[IIsTest]
      ,[IQuestNeedCnt]
      ,[IContentsLv]
      ,[IIsConfirm]
      ,[IIsSealable]
      ,[IAddDDWhenCritical]
      ,[mSealRemovalNeedCnt]
      ,[mIsPracticalPeriod]
      ,[mIsReceiveTown]
      ,[IIsReinforceDestroy]
      ,[IAddPotionRestore]
      ,[IAddMaxHpWhenTransform]
      ,[IAddMaxMpWhenTransform]
      ,[IAddAttackRateWhenTransform]
      ,[IAddMoveRateWhenTransform]
      ,[ISupportType]
      ,[ITermOfValidityLv]
      ,[mIsUseableUTGWSvr]
      ,[IAddShortAttackRange]
      ,[IAddLongAttackRange]
      ,[IWeaponPoisonType]
      ,[IDPV]
      ,[IMPV]
      ,[IRPV]
      ,[IDDV]
      ,[IMDV]
      ,[IRDV]
      ,[IHDPV]
      ,[IHMPV]
      ,[IHRPV]
      ,[IHDDV]
      ,[IHMDV]
      ,[IHRDV]
      ,[ISubDDWhenCritical]
      ,[IGetItemFeedback]
      ,[IEnemySubCriticalHit]
      ,[IIsPartyDrop]
      ,[IMaxBeadHoleCount]
      ,[ISubTypeOption]
  FROM [FNLParm].[dbo].[DT_Item]
 
 INSERT INTO [R2Parm].[dbo].[Item_EndDate]
SELECT [IID]
      ,[IName]
      ,[IType]
      ,[ILevel]
      ,[IDHIT]
      ,[IDDD]
      ,[IRHIT]
      ,[IRDD]
      ,[IMHIT]
      ,[IMDD]
      ,[IHPPlus]
      ,[IMPPlus]
      ,[ISTR]
      ,[IDEX]
      ,[IINT]
      ,[IMaxStack]
      ,[IWeight]
      ,[IUseType]
      ,[IUseNum]
      ,[IRecycle]
      ,[IHPRegen]
      ,[IMPRegen]
      ,[IAttackRate]
      ,[IMoveRate]
      ,[ICritical]
      ,[ITermOfValidity]
      ,[ITermOfValidityMi]
      ,[IDesc]
      ,[IStatus]
      ,[IFakeID]
      ,[IFakeName]
      ,[IUseMsg]
      ,[IRange]
      ,[IUseClass]
      ,[IDropEffect]
      ,[IUseLevel]
      ,[IUseEternal]
      ,[IUseDelay]
      ,[IUseInAttack]
      ,[IIsEvent]
      ,[IIsIndict]
      ,[IAddWeight]
      ,[ISubType]
      ,[IIsCharge]
      ,[INationOp]
      ,[IPShopItemType]
      ,[IQuestNo]
      ,[IIsTest]
      ,[IQuestNeedCnt]
      ,[IContentsLv]
      ,[IIsConfirm]
      ,[IIsSealable]
      ,[IAddDDWhenCritical]
      ,[mSealRemovalNeedCnt]
      ,[mIsPracticalPeriod]
      ,[mIsReceiveTown]
      ,[IIsReinforceDestroy]
      ,[IAddPotionRestore]
      ,[IAddMaxHpWhenTransform]
      ,[IAddMaxMpWhenTransform]
      ,[IAddAttackRateWhenTransform]
      ,[IAddMoveRateWhenTransform]
      ,[ISupportType]
      ,[ITermOfValidityLv]
      ,[mIsUseableUTGWSvr]
      ,[IAddShortAttackRange]
      ,[IAddLongAttackRange]
      ,[IWeaponPoisonType]
      ,[IDPV]
      ,[IMPV]
      ,[IRPV]
      ,[IDDV]
      ,[IMDV]
      ,[IRDV]
      ,[IHDPV]
      ,[IHMPV]
      ,[IHRPV]
      ,[IHDDV]
      ,[IHMDV]
      ,[IHRDV]
      ,[ISubDDWhenCritical]
      ,[IGetItemFeedback]
      ,[IEnemySubCriticalHit]
      ,[IIsPartyDrop]
      ,[IMaxBeadHoleCount]
      ,[ISubTypeOption]
  FROM [FNLParm].[dbo].[DT_Item_mEndDate]
  
 INSERT INTO [R2Parm].[dbo].[ItemAbnormalAdd]
SELECT [IID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_ItemAbnormalAdd]
 
 INSERT INTO [R2Parm].[dbo].[ItemAbnormalResist]
SELECT [IID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_ItemAbnormalResist]
 
 INSERT INTO [R2Parm].[dbo].[ItemAttributeAdd]
SELECT [IID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_ItemAttributeAdd]
 
 INSERT INTO [R2Parm].[dbo].[ItemAttributeResist]
SELECT [IID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_ItemAttributeResist]
 
 INSERT INTO [R2Parm].[dbo].[ItemBeadEffect]
SELECT [IID]
      ,[mBeadNo]
  FROM [FNLParm].[dbo].[DT_ItemBeadEffect]
  
 INSERT INTO [R2Parm].[dbo].[ItemBeadModule]
SELECT [IID]
      ,[MID]
  FROM [FNLParm].[dbo].[DT_ItemBeadModule]
  
 INSERT INTO [R2Parm].[dbo].[ItemPanalty]
SELECT [IID]
      ,[IUseClass]
      ,[IDHIT]
      ,[IDDD]
      ,[IRHIT]
      ,[IRDD]
      ,[IMHIT]
      ,[IMDD]
      ,[IHPPlus]
      ,[IMPPlus]
      ,[ISTR]
      ,[IDEX]
      ,[IINT]
      ,[IHPRegen]
      ,[IMPRegen]
      ,[IAttackRate]
      ,[IMoveRate]
      ,[ICritical]
      ,[IRange]
      ,[IAddWeight]
      ,[IAddPotionRestore]
      ,[IDPV]
      ,[IMPV]
      ,[IRPV]
      ,[IDDV]
      ,[IMDV]
      ,[IRDV]
      ,[IHDPV]
      ,[IHMPV]
      ,[IHRPV]
      ,[IHDDV]
      ,[IHMDV]
      ,[IHRDV]
  FROM [FNLParm].[dbo].[DT_ItemPanalty]
  
INSERT INTO [R2Parm].[dbo].[ItemProtect]
SELECT [IID]
      ,[PID]
  FROM [FNLParm].[dbo].[DT_ItemProtect]
 
 INSERT INTO [R2Parm].[dbo].[ItemSkill]
SELECT [IID]
      ,[SID]
      ,[SOrderNO]
  FROM [FNLParm].[dbo].[DT_ItemSkill]
 
 INSERT INTO [R2Parm].[dbo].[ItemSlain]
SELECT [IID]
      ,[SID]
  FROM [FNLParm].[dbo].[DT_ItemSlain]
 
 INSERT INTO [R2Parm].[dbo].[MaterialDrawAddGroup]
SELECT [MDRD]
      ,[mAddGroup]
      ,[mResType]
      ,[mMaxResCnt]
      ,[mSuccess]
      ,[mDesc]
  FROM [FNLParm].[dbo].[TblMaterialDrawAddGroup]
 
 INSERT INTO [R2Parm].[dbo].[MaterialDrawIndex]
SELECT [MDID]
      ,[MDRD]
      ,[mResType]
      ,[mMaxResCnt]
      ,[mSuccess]
      ,[mDesc]
      ,[mAddQuestionMark]
  FROM [FNLParm].[dbo].[TblMaterialDrawIndex]
 
 INSERT INTO [R2Parm].[dbo].[MaterialDrawMaterial]
SELECT [mSeq]
      ,[MDID]
      ,[IID]
      ,[mCnt]
  FROM [FNLParm].[dbo].[TblMaterialDrawMaterial]
 
 INSERT INTO [R2Parm].[dbo].[MaterialDrawResult]
SELECT [mSeq]
      ,[MDRD]
      ,[IID]
      ,[mPerOrRate]
      ,[mItemStatus]
      ,[mCnt]
      ,[mBinding]
      ,[mEffTime]
      ,[mValTime]
      ,[mResource]
      ,[mAddGroup]
  FROM [FNLParm].[dbo].[TblMaterialDrawResult]
 
 INSERT INTO [R2Parm].[dbo].[MaterialEnchantProbability]
SELECT [MEnchant]
      ,[MAddValue]
      ,[MReinforceFail]
  FROM [FNLParm].[dbo].[TblMaterialEnchantProbability]
 
 INSERT INTO [R2Parm].[dbo].[MaterialEvolutionGrade]
SELECT [MGrade]
      ,[MProbabilityAdd]
  FROM [FNLParm].[dbo].[TblMaterialEvolutionGrade]
 
 INSERT INTO [R2Parm].[dbo].[MaterialEvolutionMaterial]
SELECT [MEID]
      ,[MType]
      ,[MLevel]
      ,[MGrade]
      ,[mSuccess]
  FROM [FNLParm].[dbo].[TblMaterialEvolutionMaterial]
 
 INSERT INTO [R2Parm].[dbo].[MaterialEvolutionResult]
SELECT [MEID]
      ,[IID]
      ,[mPercent]
  FROM [FNLParm].[dbo].[TblMaterialEvolutionResult]
 
 INSERT INTO [R2Parm].[dbo].[MaterialItemInfo]
SELECT [IID]
      ,[MType]
      ,[MGrade]
      ,[MLevel]
      ,[MEnchant]
  FROM [FNLParm].[dbo].[TblMaterialItemInfo]
 
 INSERT INTO [R2Parm].[dbo].[MerchantSellList]
SELECT [mIndex]
      ,[ListID]
      ,[ItemID]
      ,[Price]
      ,[Flag]
      ,[SortKey]
      ,[LimitCnt]
  FROM [FNLParm].[dbo].[TblMerchantSellList]
 
 INSERT INTO [R2Parm].[dbo].[Module]
SELECT [MID]
      ,[MType]
      ,[MLevel]
      ,[MAParam]
      ,[MBParam]
      ,[MCParam]
  FROM [FNLParm].[dbo].[DT_Module]
 
 INSERT INTO [R2Parm].[dbo].[Monster]
/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [MID]
      ,[MName]
      ,[mLevel]
      ,[MClass]
      ,[MExp]
      ,[MHIT]
      ,[MMinD]
      ,[MMaxD]
      ,[MAttackRateOrg]
      ,[MMoveRateOrg]
      ,[MAttackRateNew]
      ,[MMoveRateNew]
      ,[MHP]
      ,[MMP]
      ,[MMoveRange]
      ,[MGbjType]
      ,[MRaceType]
      ,[MAiType]
      ,[MCastingDelay]
      ,[MChaotic]
      ,[MSameRace1]
      ,[MSameRace2]
      ,[MSameRace3]
      ,[MSameRace4]
      ,[mSightRange]
      ,[mAttackRange]
      ,[mSkillRange]
      ,[mBodySize]
      ,[mDetectTransF]
      ,[mDetectTransP]
      ,[mDetectChao]
      ,[mAiEx]
      ,[mScale]
      ,[mIsResistTransF]
      ,[mIsEvent]
      ,[mIsTest]
      ,[mHPNew]
      ,[mMPNew]
      ,[mBuyMerchanID]
      ,[mSellMerchanID]
      ,[mChargeMerchanID]
      ,[mTransformWeight]
      ,[mNationOp]
      ,[mHPRegen]
      ,[mMPRegen]
      ,[IContentsLv]
      ,[mIsEventTest]
      ,[mIsShowHp]
      ,[mSupportType]
      ,[mVolitionOfHonor]
      ,[mWMapIconType]
      ,[mIsAmpliableTermOfValidity]
      ,[mAttackType]
      ,[mTransType]
      ,[mDPV]
      ,[mMPV]
      ,[mRPV]
      ,[mDDV]
      ,[mMDV]
      ,[mRDV]
      ,[mSubDDWhenCritical]
      ,[mEnemySubCriticalHit]
      ,[mEventQuest]
  FROM [FNLParm].[dbo].[DT_Monster]
 
INSERT INTO [R2Parm].[dbo].[MonsterAbnormalAdd]
SELECT [MID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_MonsterAbnormalAdd]
 
INSERT INTO [R2Parm].[dbo].[MonsterAbnormalResist]
SELECT [MID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_MonsterAbnormalResist]
 
INSERT INTO [R2Parm].[dbo].[MonsterAttributeAdd]
SELECT [MID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_MonsterAttributeAdd]
 
INSERT INTO [R2Parm].[dbo].[MonsterAttributeResist]
SELECT [MID]
      ,[AID]
  FROM [FNLParm].[dbo].[DT_MonsterAttributeResist]

INSERT INTO [R2Parm].[dbo].[MonsterDrop]
SELECT [MID]
      ,[DGroup]
      ,[DPercent]
  FROM [FNLParm].[dbo].[DT_MonsterDrop]

INSERT INTO [R2Parm].[dbo].[MonsterRole]
SELECT [MID]
      ,[mRole]
  FROM [FNLParm].[dbo].[DT_MonsterRole]

INSERT INTO [R2Parm].[dbo].[MonsterSlain]
SELECT [MID]
      ,[SID]
  FROM [FNLParm].[dbo].[DT_MonsterSlain]

INSERT INTO [R2Parm].[dbo].[MonsterSpot]
SELECT [mGID]
      ,[mMID]
      ,[mCnt]
      ,[mTick]
      ,[mDir]
      ,[mVarRespawnTick]
  FROM [FNLParm].[dbo].[TblMonsterSpot]

INSERT INTO [R2Parm].[dbo].[MonsterSpotGroup]
SELECT [mGID]
      ,[mPosX]
      ,[mPosY]
      ,[mPosZ]
      ,[mRadius]
  FROM [FNLParm].[dbo].[TblMonsterSpotGroup]

INSERT INTO [R2Parm].[dbo].[Protect]
SELECT [SID]
      ,[SType]
      ,[SLevel]
      ,[SDPV]
      ,[SMPV]
      ,[SRPV]
      ,[SDDV]
      ,[SMDV]
      ,[SRDV]
  FROM [FNLParm].[dbo].[DT_Protect]

INSERT INTO [R2Parm].[dbo].[Quest]
SELECT [mQuestNo]
      ,[mQuestNm]
      ,[mClass]
      ,[mLevel1]
      ,[mLevel2]
      ,[mPreQuestNo]
      ,[mIsOverlap]
      ,[mQuestDesc]
      ,[mAbandonment]
      ,[mDifficulty]
      ,[mRewardNo]
      ,[mScriptType]
      ,[mPlace]
      ,[mPosX]
      ,[mPosY]
      ,[mPosZ]
      ,[mVisible]
      ,[mTextNo]
      ,[mParentNo]
      ,[mFindNPC]
      ,[mCompletionNPC]
      ,[mQuestKind]
  FROM [FNLParm].[dbo].[TblQuest]

INSERT INTO [R2Parm].[dbo].[QuestCondition]
SELECT [mQuestNo]
      ,[mType]
      ,[mID]
      ,[mCnt]
      ,[mDesc]
      ,[mSeqNo]
  FROM [FNLParm].[dbo].[TblQuestCondition]

INSERT INTO [R2Parm].[dbo].[QuestInfo]
SELECT [mQuestNo]
      ,[mType]
      ,[mParmA]
      ,[mParmB]
      ,[mParmC]
      ,[mDesc]
      ,[mSeqNo]
  FROM [FNLParm].[dbo].[TblQuestInfo]

INSERT INTO [R2Parm].[dbo].[QuestRefMonster]
SELECT [mQuestNo]
      ,[mMonsterID]
  FROM [FNLParm].[dbo].[TblQuestRefMonster]

INSERT INTO [R2Parm].[dbo].[QuestReward]
SELECT [mRewardNo]
      ,[mExp]
      ,[mID]
      ,[mCnt]
      ,[mBinding]
      ,[mStatus]
      ,[mEffTime]
      ,[mValTime]
  FROM [FNLParm].[dbo].[TblQuestReward]

INSERT INTO [R2Parm].[dbo].[Refine]
SELECT [RID]
      ,[RItemID0]
      ,[RItemID1]
      ,[RItemID2]
      ,[RItemID3]
      ,[RItemID4]
      ,[RItemID5]
      ,[RItemID6]
      ,[RItemID7]
      ,[RItemID8]
      ,[RItemID9]
      ,[RSuccess]
      ,[RIsCreateCnt]
  FROM [FNLParm].[dbo].[DT_Refine]

INSERT INTO [R2Parm].[dbo].[RefineCreateInfo]
SELECT [mIDX]
      ,[mRID]
      ,[mGroup1]
      ,[mGroup2]
      ,[mSort]
      ,[mItem0]
      ,[mItem1]
      ,[mItem2]
      ,[mItem3]
      ,[mCost]
  FROM [FNLParm].[dbo].[DT_RefineCreateInfo]

INSERT INTO [R2Parm].[dbo].[RefineMaterial]
SELECT [RID]
      ,[RItemID]
      ,[RNum]
      ,[ROrderNo]
  FROM [FNLParm].[dbo].[DT_RefineMaterial]

INSERT INTO [R2Parm].[dbo].[RegionOptions]
SELECT [mPlace]
      ,[mIsSupport]
      ,[mExpRate]
      ,[mMonsterItemDropRate]
      ,[mShowPlayerName]
      ,[mMonSilverDropRate]
      ,[mNoDropItemOnDeath]
      ,[mNoExpDescOnDeath]
  FROM [FNLParm].[dbo].[TblRegionOptions]

INSERT INTO [R2Parm].[dbo].[RegionQuest]
SELECT [mQuestNo]
      ,[mQuestNm]
      ,[mQuestNmKey]
  FROM [FNLParm].[dbo].[TblRegionQuest]

INSERT INTO [R2Parm].[dbo].[RegionQuestCondition]
SELECT [mQuestNo]
      ,[mParmID]
      ,[mBoss]
      ,[mStepCnt]
      ,[mStep1]
      ,[mStep2]
      ,[mStep3]
      ,[mTotalCnt]
  FROM [FNLParm].[dbo].[TblRegionQuestCondition]

INSERT INTO [R2Parm].[dbo].[RegionQuestPlace]
SELECT [mQuestNo]
      ,[mPlace]
  FROM [FNLParm].[dbo].[TblRegionQuestPlace]

INSERT INTO [R2Parm].[dbo].[RoomInfo]
SELECT [mID]
      ,[MName]
      ,[mType]
      ,[mMapNo]
      ,[mKeyItem]
  FROM [FNLParm].[dbo].[TblRoomInfo]

INSERT INTO [R2Parm].[dbo].[Skill]
SELECT [SID]
      ,[SName]
      ,[SHitPlus]
      ,[SMPPerUse]
      ,[SSpellNum]
      ,[SDesc]
      ,[SType]
      ,[SHPPerUse]
      ,[SChaoUse]
      ,[mApplyRadius]
      ,[mApplyCnt]
      ,[mApplyRace]
      ,[mCastingDelay]
      ,[mConsumeItem]
      ,[mConsumeItemCnt]
      ,[mActiveType]
      ,[mAnimation]
      ,[mCastingSpeed]
      ,[mSkillEffect]
      ,[mCAmShakeWhenHit]
      ,[mCriticalEffectWhenHit]
      ,[mActiveWeapon]
      ,[mCoolTime]
      ,[mCastingGroup]
      ,[mCoolTimeGroup]
      ,[mConsumeItem2]
      ,[mConsumeItemCnt2]
      ,[mIsCancel]
      ,[mIsAttack]
  FROM [FNLParm].[dbo].[DT_Skill]

INSERT INTO [R2Parm].[dbo].[SkillAbnormal]
SELECT [SID]
      ,[AbnormalID]
  FROM [FNLParm].[dbo].[DT_SkillAbnormal]

INSERT INTO [R2Parm].[dbo].[SkillAttribute]
SELECT [SID]
      ,[AttrbuteID]
  FROM [FNLParm].[dbo].[DT_SkillAttribute]

INSERT INTO [R2Parm].[dbo].[SkillEnhancement]
SELECT [mESPID]
      ,[mSPID]
      ,[mOrderNo]
      ,[mUseClass]
  FROM [FNLParm].[dbo].[DT_SkillEnhancement]

INSERT INTO [R2Parm].[dbo].[SkillEnhancementMaterial]
SELECT [mESPID]
      ,[mOrderNo]
      ,[mItemID]
      ,[mCnt]
  FROM [FNLParm].[dbo].[DT_SkillEnhancementMaterial]

INSERT INTO [R2Parm].[dbo].[SkillIgnoreCastingDelayGroup]
SELECT [SGroupNo]
      ,[SIgnoreGroup]
  FROM [FNLParm].[dbo].[DT_SkillIgnoreCastingDelayGroup]

INSERT INTO [R2Parm].[dbo].[SkillIgnoreCoolTimeGroup]
SELECT [SGroupNo]
      ,[SIgnoreGroup]
  FROM [FNLParm].[dbo].[DT_SkillIgnoreCoolTimeGroup]

INSERT INTO [R2Parm].[dbo].[SkillPack]
SELECT [mSPID]
      ,[mName]
      ,[mIType]
      ,[mIUseType]
      ,[mISubType]
      ,[mTermOfValidity]
      ,[mDesc]
      ,[mUseMsg]
      ,[mUseRange]
      ,[mUseClass]
      ,[mUseLevel]
      ,[mSpriteFile]
      ,[mSpriteX]
      ,[mSpriteY]
      ,[mIsUseableUTGWSvr]
      ,[mUseInAttack]
      ,[mIsDrop]
  FROM [FNLParm].[dbo].[DT_SkillPack]

INSERT INTO [R2Parm].[dbo].[SkillPackSkill]
SELECT [mSPID]
      ,[mSID]
      ,[mSOrderNO]
  FROM [FNLParm].[dbo].[DT_SkillPackSkill]

INSERT INTO [R2Parm].[dbo].[SkillResource]
SELECT [RID]
      ,[ROwnerID]
      ,[RType]
      ,[RFileName]
      ,[RPosX]
      ,[RPosY]
  FROM [FNLParm].[dbo].[DT_SkillResource]

INSERT INTO [R2Parm].[dbo].[SkillSlain]
SELECT [SkillID]
      ,[SlainID]
  FROM [FNLParm].[dbo].[DT_SkillSlain]

INSERT INTO [R2Parm].[dbo].[SkillTreeNode]
SELECT [mSTNID]
      ,[mSTID]
      ,[mName]
      ,[mMaxLevel]
      ,[mNodeType]
      ,[mIconSlotX]
      ,[mIconSlotY]
      ,[mLineN]
      ,[mLineE]
      ,[mLineS]
      ,[mLineW]
      ,[mTermOfValidity]
  FROM [FNLParm].[dbo].[DT_SkillTreeNode]

INSERT INTO [R2Parm].[dbo].[SkillTreeNodeItem]
SELECT [mSTNIID]
      ,[mSTNID]
      ,[mSPID]
      ,[mLevel]
  FROM [FNLParm].[dbo].[DT_SkillTreeNodeItem]

INSERT INTO [R2Parm].[dbo].[SkillTreeNodeItemCondition]
SELECT [mSTNIID]
      ,[mSTNICType]
      ,[mParamA]
      ,[mParamB]
      ,[mParamC]
  FROM [FNLParm].[dbo].[DT_SkillTreeNodeItemCondition]

INSERT INTO [R2Parm].[dbo].[SkillType]
SELECT [SType]
      ,[SName]
  FROM [FNLParm].[dbo].[TP_SkillType]

INSERT INTO [R2Parm].[dbo].[Slain]
SELECT [SID]
      ,[SType]
      ,[SLevel]
      ,[SHitPlus]
      ,[SDDPlus]
      ,[SRDDPlus]
      ,[SRHitPlus]
  FROM [FNLParm].[dbo].[DT_Slain]

INSERT INTO [R2Parm].[dbo].[SlainType]
SELECT [SType]
      ,[SName]
  FROM [FNLParm].[dbo].[TP_SlainType]

INSERT INTO [R2Parm].[dbo].[TransformAbilityByLevel]
SELECT [mLevel]
      ,[mMaxHP]
      ,[mMaxMP]
      ,[mMaxWeight]
      ,[mShortAttackRate]
      ,[mLongAttackRate]
      ,[mMoveRate]
      ,[mType]
  FROM [FNLParm].[dbo].[TblTransformAbilityByLevel]

INSERT INTO [R2Parm].[dbo].[TransformList]
SELECT [mNo]
      ,[mGroupID]
      ,[mMonID]
      ,[mLevel]
      ,[mEq0]
      ,[mEq1]
      ,[mEq2]
      ,[mEq3]
      ,[mEq4]
      ,[mEq5]
      ,[mEq6]
      ,[mEq7]
      ,[mEq8]
      ,[mEq9]
      ,[mEq10]
      ,[mControl]
  FROM [FNLParm].[dbo].[TblTransformList]







