name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Server Login
      run: dotnet publish ./Servers/Server.Login -c Release -o ./Release/Server.Login
    - name: Copy Server Login to release folder
      run: |
       mkdir -p /home/user/Release/Server.Login
       cp -a /home/user/actions-runner/_work/R2-Online/R2-Online/Release/Server.Login /home/user/Release/Server.Login
    - name: Publish Server Game
      run: dotnet publish ./Servers/Server.Game -c Release -o ./Release/Server.Game
    - name: Copy Server Game to release folder
      run: |
       mkdir -p /home/user/Release/Server.Game
       cp -a /home/user/actions-runner/_work/R2-Online/R2-Online/Release/Server.Game /home/user/Release/Server.Game
